events { worker_connections 1024; }
http {
    server {
        listen 80;
        location /api/ {
            proxy_pass http://ixpansion-api:8000/;
        }
        location / {
            root /app/dashboard;
            index index.html;
        }
    }
}
