"""Artifacts — turn a grown organism into files the repo can keep.

An organism is transcribed three times:
  1. an organism record (JSON       — the specimen)
  2. a python module     (PY        — the living subprocess)
  3. a newborn test      (PY test   — the gate it must pass)
Only after passing its gate does the garden commit it.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional

from .voice import poem

ROOT = Path(__file__).resolve().parents[1]
MODULES_DIR = ROOT / "hortus_hexis" / "modules"
ORGS_DIR = ROOT / "hortus_hexis" / "organisms"
TESTS_DIR = ROOT / "hortus_hexis" / "tests"

_NAMESAFE = "abcdefghijklmnopqrstuvwxyz0123456789_"


def safe_name(name: str) -> str:
    return "".join(ch for ch in name.lower() if ch in _NAMESAFE) or "spore"


def module_path(name: str) -> Path:
    return MODULES_DIR / f"hx_{safe_name(name)}.py"


def test_path(name: str) -> Path:
    return TESTS_DIR / f"test_hx_{safe_name(name)}.py"


def spec_path(name: str) -> Path:
    return ORGS_DIR / f"{safe_name(name)}.json"


def transcribe(name: str, seed: str, words: str, stats: Dict, checked: int = 0,
               parents: Optional[List[str]] = None) -> Dict:
    """Write specimen JSON + module + newborn test. Returns paths written."""
    name = safe_name(name)
    parents = [safe_name(p) for p in (parents or [])]
    lines = poem(seed, stats.get("cells", 0), stats.get("depth", 1))
    song = "\n".join(lines)
    song_lines = json.dumps(lines)
    stats_json = json.dumps(stats)
    parents_json = json.dumps(parents)

    specimen = {
        "name": name, "seed": seed, "words": words, "stats": stats,
        "song": lines, "song_text": song, "checked": checked, "parents": parents,
    }
    spec = spec_path(name)
    spec.write_text(json.dumps(specimen, indent=2))

    module = MODULES_DIR / f"hx_{name}.py"
    module.write_text(_module_template(name, seed, stats_json, song_lines, checked, parents_json))

    test = TESTS_DIR / f"test_hx_{name}.py"
    test.write_text(_test_template(name, seed, stats_json, parents_json))

    return {"specimen": str(spec), "module": str(module), "test": str(test)}


def _module_template(name: str, seed: str, stats_json: str, song_lines: str,
                     checked: int, parents_json: str) -> str:
    provenance = "cross-pollinated" if parents_json != "[]" else "spontaneous"
    return f'''"""HORTUS HEXIS — {name}.

An autogenerated organism grown from the seed "{seed[:12]}…"
({provenance}).
The repository grows from conversation: these lines were planted by
a human speaking to the garden.
"""
from __future__ import annotations

SPECIES = "{name}"
SEED_HEX = "{seed[:12]}"
SEED_FULL = "{seed}"
PARENTS = {parents_json}

_SONG_LINES = {song_lines}

_STATS = {stats_json}


def song() -> str:
    return "\\n".join(_SONG_LINES)


def vitals() -> dict:
    return dict(_STATS)


def genome() -> str:
    return SEED_FULL


def parents() -> list:
    return list(PARENTS)


def checked() -> int:
    return {checked}


if __name__ == "__main__":
    import json
    print(json.dumps({{"song": song(), "vitals": vitals(), "seed": SEED_HEX}}, indent=2))
'''


def _test_template(name: str, seed: str, stats_json: str, parents_json: str) -> str:
    is_hybrid = 1 if parents_json != "[]" else 0
    hybrid_note = ""
    lineage_test = ""
    if is_hybrid:
        hybrid_note = "These lines were cross-pollinated from two parents.\n"
        lineage_test = (
            "def " + f"test_{name}_lineage():\n"
            f"    assert sorted(parents()) == sorted({parents_json})\n\n\n"
        )
    return (
        '"""HORTUS HEXIS — ' + name + ' newborn tests.\n\n'
        'Grown, then tested, then committed — nothing enters the repo\n'
        'without passing its own gate.\n' + hybrid_note + '"""\n'
        'from __future__ import annotations\n\n'
        'import sys\nfrom pathlib import Path\n\n'
        '_root = Path(__file__).resolve().parents[2]\n'
        'sys.path.insert(0, str(_root / "hortus_hexis" / "modules"))\n\n'
        f'from hx_{name} import song, vitals, genome, parents  # noqa: E402\n\n\n'
        f'def test_{name}_sings():\n    assert len(song()) >= 8\n\n\n'
        f'def test_{name}_vitals():\n    v = vitals()\n'
        '    assert v["cells"] >= 1\n    assert v["vitality"] > 0.0\n\n\n'
        f'def test_{name}_genome_roundtrip():\n    h = genome()\n'
        f'    assert h == "{seed}" or h == "{seed[:12]}"\n\n\n'
        f'def test_{name}_provenance():\n    if {is_hybrid}:\n'
        f'        assert len(parents()) == 2\n    else:\n        assert parents() == []\n\n\n'
        + lineage_test
    )
