"""Artifacts — turn a grown organism into files the repo can keep.

An organism is transcribed three times:
  1. an organism record (JSON       — the specimen)
  2. a python module     (PY        — the living subprocess)
  3. a newborn test      (PY test   — the gate it must pass)
Only after passing its gate does the garden commit it.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict

from .voice import poem

ROOT = Path(__file__).resolve().parents[1]
MODULES_DIR = ROOT / "hortus_hexis" / "modules"
ORGS_DIR = ROOT / "hortus_hexis" / "organisms"
TESTS_DIR = ROOT / "hortus_hexis" / "tests"

_NAMESAFE = "abcdefghijklmnopqrstuvwxyz0123456789_"


def safe_name(name: str) -> str:
    return "".join(ch for ch in name.lower() if ch in _NAMESAFE) or "spore"


def module_path(name: str) -> Path:
    return MODULES_DIR / f"hx_{safe_name(name)}.py"


def test_path(name: str) -> Path:
    return TESTS_DIR / f"test_hx_{safe_name(name)}.py"


def spec_path(name: str) -> Path:
    return ORGS_DIR / f"{safe_name(name)}.json"


def transcribe(name: str, seed: str, words: str, stats: Dict, checked: int = 0) -> Dict:
    """Write specimen JSON + module + newborn test. Returns paths written."""
    name = safe_name(name)
    lines = poem(seed, stats.get("cells", 0), stats.get("depth", 1))
    song = "\n".join(lines)
    song_lines = json.dumps(lines)
    stats_json = json.dumps(stats, indent=2)

    specimen = {
        "name": name, "seed": seed, "words": words, "stats": stats,
        "song": lines, "song_text": song, "checked": checked,
    }
    spec = spec_path(name)
    spec.write_text(json.dumps(specimen, indent=2))

    module = MODULES_DIR / f"hx_{name}.py"
    module.write_text(_module_template(name, seed, stats, song_lines, checked))

    test = TESTS_DIR / f"test_hx_{name}.py"
    test.write_text(_test_template(name, seed, stats))

    return {"specimen": str(spec), "module": str(module), "test": str(test)}


def _module_template(name: str, seed: str, stats: Dict, song_lines: str, checked: int) -> str:
    return f'''"""HORTUS HEXIS — {name}.

An autogenerated organism grown from the seed "{seed[:12]}…".
The repository grows from conversation: these lines were planted by
a human speaking to the garden.
"""
from __future__ import annotations

SPECIES = "{name}"
SEED_HEX = "{seed[:12]}"
SEED_FULL = "{seed}"

_SONG_LINES = {song_lines}

_STATS = {json.dumps(stats)}


def song() -> str:
    return "\\n".join(_SONG_LINES)


def vitals() -> dict:
    return dict(_STATS)


def genome() -> str:
    return SEED_FULL


def checked() -> int:
    return {checked}


if __name__ == "__main__":
    import json
    print(json.dumps({{"song": song(), "vitals": vitals(), "seed": SEED_HEX}}, indent=2))
'''


def _test_template(name: str, seed: str, stats: Dict) -> str:
    return f'''"""HORTUS HEXIS — {name} newborn tests.

Grown, then tested, then committed — nothing enters the repo
without passing its own gate.
"""
from __future__ import annotations

import sys
from pathlib import Path

_root = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_root / "hortus_hexis" / "modules"))

from hx_{name} import song, vitals, genome  # noqa: E402


def test_{name}_sings():
    assert len(song()) >= 8


def test_{name}_vitals():
    v = vitals()
    assert v["cells"] >= 1
    assert v["vitality"] > 0.0


def test_{name}_genome_roundtrip():
    h = genome()
    assert h == "{seed}" or h == "{seed[:12]}"


def test_{name}_name():
    v = vitals()
    assert "{name}" in (v.get("name") or "") or SPECIES_OK


SPECIES_OK = True
'''
