"""HORTUS HEXIS — amarnysxeth.

An autogenerated organism grown from the seed "7265736f6e61…".
The repository grows from conversation: these lines were planted by
a human speaking to the garden.
"""
from __future__ import annotations

SPECIES = "amarnysxeth"
SEED_HEX = "7265736f6e61"
SEED_FULL = "7265736f6e616e63652069732061207269766572206f66206c69676874"

_SONG_LINES = ["velnia velnia haunts in drak light", "velnia velnia drifts in amar light", "velnia velnia haunts in sil light", "velnia urion drifts in nys light", "\u2014 amarnysxeth, grown from 7265736f6e\u2026"]

_STATS = {"name": "amarnysxeth", "seed": "7265736f6e616e63652069732061207269766572206f66206c69676874", "words": "resonance is a river of light", "cells": 4, "vitality": 0.43, "grown_ms": 109.3, "checked": 0}


def song() -> str:
    return "\n".join(_SONG_LINES)


def vitals() -> dict:
    return dict(_STATS)


def genome() -> str:
    return SEED_FULL


def checked() -> int:
    return 0


if __name__ == "__main__":
    import json
    print(json.dumps({"song": song(), "vitals": vitals(), "seed": SEED_HEX}, indent=2))
