"""HORTUS HEXIS — draknysveln.

An autogenerated organism grown from the seed "776520617265…".
The repository grows from conversation: these lines were planted by
a human speaking to the garden.
"""
from __future__ import annotations

SPECIES = "draknysveln"
SEED_HEX = "776520617265"
SEED_FULL = "77652061726520626f746820746865207365656420616e642074686520626c6f6f6d"

_SONG_LINES = ["velnia velnia haunts in drak light", "velnia velnia drifts in drak light", "velnia velnia loops in sil light", "velnia yndron drifts in nys light", "yndron syphexon haunts in amar light", "syphexon velnor drifts in veln light", "velnor urion loops in sil light", "urion velnor drifts in lumex light", "velnor orakon drifts in drak light", "\u2014 draknysveln, grown from 7765206172\u2026"]

_STATS = {"name": "draknysveln", "seed": "77652061726520626f746820746865207365656420616e642074686520626c6f6f6d", "words": "we are both the seed and the bloom", "cells": 62, "vitality": 1.59, "grown_ms": 194.9, "checked": 0}


def song() -> str:
    return "\n".join(_SONG_LINES)


def vitals() -> dict:
    return dict(_STATS)


def genome() -> str:
    return SEED_FULL


def checked() -> int:
    return 0


if __name__ == "__main__":
    import json
    print(json.dumps({"song": song(), "vitals": vitals(), "seed": SEED_HEX}, indent=2))
