"""HORTUS HEXIS — kalyndnysorev.

An autogenerated organism grown from the seed "010d085c014b…"
(cross-pollinated).
The repository grows from conversation: these lines were planted by
a human speaking to the garden.
"""
from __future__ import annotations

SPECIES = "kalyndnysorev"
SEED_HEX = "010d085c014b"
SEED_FULL = "010d085c014b4f115f5e34293135421b151a1be8eef6e881dcc7dfcee4a8bdb796829c869d77637e76c5ffe54dfa666559"
PARENTS = ["kalyndramar", "syphexnysorev"]

_SONG_LINES = ["velnia velnia blooms in veln light", "velnia velnia blooms in lumex light", "velnia velnia blooms in veln light", "velnia nyson weaves in kal light", "nyson vedhar blooms in veln light", "vedhar nyson cracks in uri light", "nyson nysis cracks in nys light", "nysis orakar curls in syphex light", "orakar drakar weaves in veln light", "\u2014 lumexkaluri, grown from 010d085c01\u2026"]

_STATS = {"name": "kalyndnysorev", "seed": "010d085c014b4f115f5e34293135421b151a1be8eef6e881dcc7dfcee4a8bdb796829c869d77637e76c5ffe54dfa666559", "words": "hybrid:kalyndramar+syphexnysorev", "cells": 11, "vitality": 0.57, "grown_ms": 304.7, "checked": 0}


def song() -> str:
    return "\n".join(_SONG_LINES)


def vitals() -> dict:
    return dict(_STATS)


def genome() -> str:
    return SEED_FULL


def parents() -> list:
    return list(PARENTS)


def checked() -> int:
    return 0


if __name__ == "__main__":
    import json
    print(json.dumps({"song": song(), "vitals": vitals(), "seed": SEED_HEX}, indent=2))
