"""HORTUS HEXIS — kalyndramar.

An autogenerated organism grown from the seed "6d6f726969…".
The repository grows from conversation: these lines were planted by
a human speaking to the garden.
"""
from __future__ import annotations

SPECIES = "kalyndramar"
SEED_HEX = "6d6f726969"
SEED_FULL = "6d6f726969"

_SONG_LINES = ["velnia velnia drifts in sil light", "velnia velnia drifts in kal light", "velnia velnia haunts in sil light", "velnia qoon drifts in yndr light", "qoon yndron drifts in drak light", "yndron velnia weaves in amar light", "velnia velnia haunts in sil light", "velnia velnia loops in qo light", "velnia velnia curls in sil light", "\u2014 kalyndramar, grown from 6d6f726969\u2026"]

_STATS = {"name": "kalyndramar", "seed": "6d6f726969", "words": "morii", "cells": 10, "vitality": 0.55, "grown_ms": 134.9, "checked": 0}


def song() -> str:
    return "\n".join(_SONG_LINES)


def vitals() -> dict:
    return dict(_STATS)


def genome() -> str:
    return SEED_FULL


def checked() -> int:
    return 0


if __name__ == "__main__":
    import json
    print(json.dumps({"song": song(), "vitals": vitals(), "seed": SEED_HEX}, indent=2))
