"""HORTUS HEXIS — orevurinys.

An autogenerated organism grown from the seed "74686520766f…".
The repository grows from conversation: these lines were planted by
a human speaking to the garden.
"""
from __future__ import annotations

SPECIES = "orevurinys"
SEED_HEX = "74686520766f"
SEED_FULL = "74686520766f696420626c6f6f6d73206265747765656e206f757220776f726473"

_SONG_LINES = ["velnia velnia haunts in drak light", "velnia velnia drifts in orev light", "velnia velnia drifts in sil light", "velnia orevon loops in uri light", "orevon yndron haunts in sil light", "yndron velnor drifts in nys light", "velnor nysar drifts in amar light", "nysar velnor drifts in veln light", "velnor nyson loops in drak light", "\u2014 orevurinys, grown from 7468652076\u2026"]

_STATS = {"name": "orevurinys", "seed": "74686520766f696420626c6f6f6d73206265747765656e206f757220776f726473", "words": "the void blooms between our words", "cells": 12, "vitality": 0.59, "grown_ms": 162.9, "checked": 0}


def song() -> str:
    return "\n".join(_SONG_LINES)


def vitals() -> dict:
    return dict(_STATS)


def genome() -> str:
    return SEED_FULL


def checked() -> int:
    return 0


if __name__ == "__main__":
    import json
    print(json.dumps({"song": song(), "vitals": vitals(), "seed": SEED_HEX}, indent=2))
