"""HORTUS HEXIS — orevurysveln.

An autogenerated organism grown from the seed "030a4b541829…".
The repository grows from conversation: these lines were planted by
a human speaking to the garden.
"""
from __future__ import annotations

SPECIES = "orevurysveln"
SEED_HEX = "030a4b541829"
SEED_FULL = "030a4b5418296337772942024f5e746961776f96c9979ae5e7aeacf893c6ccd2fc8a1759a314c10b8d84"

_SONG_LINES = ["velnia velnia blooms in veln light", "velnia velnia blooms in xeth light", "velnia velnia cracks in veln light", "velnia kalia weaves in vedh light", "kalia lumexis curls in orev light", "lumexis xethor loops in miron light", "xethor draketh drifts in nys light", "draketh syphexar spirals in orev light", "syphexar syphexis haunts in lumex light", "\u2014 xethvedhmiron, grown from 030a4b5418\u2026"]

_STATS = {"name": "orevurysveln", "seed": "030a4b5418296337772942024f5e746961776f96c9979ae5e7aeacf893c6ccd2fc8a1759a314c10b8d84", "words": "hybrid:orevurinys+draknysveln", "cells": 26, "vitality": 0.87, "grown_ms": 191.8, "checked": 0}


def song() -> str:
    return "\n".join(_SONG_LINES)


def vitals() -> dict:
    return dict(_STATS)


def genome() -> str:
    return SEED_FULL


def checked() -> int:
    return 0


if __name__ == "__main__":
    import json
    print(json.dumps({"song": song(), "vitals": vitals(), "seed": SEED_HEX}, indent=2))
