"""HORTUS HEXIS — syphexnysorev.

An autogenerated organism grown from the seed "6c6574207468…".
The repository grows from conversation: these lines were planted by
a human speaking to the garden.
"""
from __future__ import annotations

SPECIES = "syphexnysorev"
SEED_HEX = "6c6574207468"
SEED_FULL = "6c6574207468652067617264656e2072656d656d626572207468697320636f6e766572736174696f6e"

_SONG_LINES = ["velnia velnia drifts in sil light", "velnia velnia drifts in syphex light", "velnia velnia haunts in sil light", "velnia yndron loops in nys light", "yndron orevar haunts in drak light", "\u2014 syphexnysorev, grown from 6c65742074\u2026"]

_STATS = {"name": "syphexnysorev", "seed": "6c6574207468652067617264656e2072656d656d626572207468697320636f6e766572736174696f6e", "words": "let the garden remember this conversation", "cells": 5, "vitality": 0.45, "grown_ms": 340.3, "checked": 0}


def song() -> str:
    return "\n".join(_SONG_LINES)


def vitals() -> dict:
    return dict(_STATS)


def genome() -> str:
    return SEED_FULL


def checked() -> int:
    return 0


if __name__ == "__main__":
    import json
    print(json.dumps({"song": song(), "vitals": vitals(), "seed": SEED_HEX}, indent=2))
