"""HORTUS HEXIS — velnsyphexlumex.

An autogenerated organism grown from the seed "706c616e7420…"
(spontaneous).
The repository grows from conversation: these lines were planted by
a human speaking to the garden.
"""
from __future__ import annotations

SPECIES = "velnsyphexlumex"
SEED_HEX = "706c616e7420"
SEED_FULL = "706c616e74206120636f6e7374656c6c6174696f6e207365656420696e207468652067617264656e"
PARENTS = []

_SONG_LINES = ["velnia velnia haunts in drak light", "velnia velnia drifts in veln light", "velnia velnia drifts in sil light", "velnia nyson drifts in syphex light", "nyson amarar haunts in sil light", "amarar drakon loops in lumex light", "drakon nyson drifts in sil light", "nyson orevar loops in orak light", "orevar orakon drifts in drak light", "\u2014 velnsyphexlumex, grown from 706c616e74\u2026"]

_STATS = {"name": "velnsyphexlumex", "seed": "706c616e74206120636f6e7374656c6c6174696f6e207365656420696e207468652067617264656e", "words": "plant a constellation seed in the garden", "cells": 38, "vitality": 1.11, "grown_ms": 337.1, "checked": 0}


def song() -> str:
    return "\n".join(_SONG_LINES)


def vitals() -> dict:
    return dict(_STATS)


def genome() -> str:
    return SEED_FULL


def parents() -> list:
    return list(PARENTS)


def checked() -> int:
    return 0


if __name__ == "__main__":
    import json
    print(json.dumps({"song": song(), "vitals": vitals(), "seed": SEED_HEX}, indent=2))
