"""Data Licensing — sell experiment results and dataset access.

License unique datasets generated by experiments: consciousness fields,
quantum states, cosmic maps, ecosystem simulations. Researchers and
companies pay for access to these unique datasets.

Usage:
    GET  /api/data/catalog      — browse available datasets
    POST /api/data/purchase     — buy dataset access
    GET  /api/data/<id>/download — download dataset (requires license)
    GET  /api/data/subscriptions — recurring dataset access plans
"""
from __future__ import annotations

import hashlib
import json
import time
import sys
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

CATALOG_FILE = ROOT / ".runtime" / "data_catalog.json"
LICENSES_FILE = ROOT / ".runtime" / "data_licenses.json"

DATASET_CATALOG = [
    {
        "id": "consciousness_field_15x15",
        "name": "Consciousness Field 15x15 Grid",
        "description": "15x15 continuous awareness field simulation data",
        "category": "consciousness",
        "format": "json",
        "size_mb": 2.4,
        "rows": 22500,
        "price_usd": 49.00,
        "license": "research",
        "sample": {"grid_size": [15, 15], "awareness_levels": 8},
    },
    {
        "id": "quantum_superposition_states",
        "name": "Quantum Superposition State Vectors",
        "description": "Complex amplitude vectors for 64-qubit simulation",
        "category": "quantum",
        "format": "json",
        "size_mb": 12.8,
        "rows": 64000,
        "price_usd": 99.00,
        "license": "commercial",
        "sample": {"qubits": 64, "state_vectors": 64},
    },
    {
        "id": "cosmic_web_galaxies",
        "name": "Cosmic Web Galaxy Mapping Dataset",
        "description": "Galaxy clusters, filaments, and voids from cosmic web mapper",
        "category": "cosmology",
        "format": "csv",
        "size_mb": 8.1,
        "rows": 50000,
        "price_usd": 79.00,
        "license": "research",
        "sample": {"galaxies": 150, "filaments": 45, "voids": 23},
    },
    {
        "id": "meme_evolution_20gens",
        "name": "Meme Evolution 20-Generation Dataset",
        "description": "20 memes evolving across 20 generations with fitness tracking",
        "category": "evolution",
        "format": "json",
        "size_mb": 1.2,
        "rows": 400,
        "price_usd": 29.00,
        "license": "research",
        "sample": {"memes": 20, "generations": 20},
    },
    {
        "id": "neural_plasticity_pathways",
        "name": "Neural Plasticity Pathway Traces",
        "description": "Self-organizing neural pathway evolution data",
        "category": "neuroscience",
        "format": "json",
        "size_mb": 5.6,
        "rows": 25000,
        "price_usd": 59.00,
        "license": "commercial",
        "sample": {"pathways": 128, "evolution_steps": 500},
    },
    {
        "id": "gravitational_lens_sim",
        "name": "Gravitational Lensing Simulation Data",
        "description": "Execution path bending through simulated gravity wells",
        "category": "physics",
        "format": "json",
        "size_mb": 3.3,
        "rows": 15000,
        "price_usd": 39.00,
        "license": "research",
        "sample": {"lenses": 10, "paths_bent": 500},
    },
    {
        "id": "dream_archaeology_50artifacts",
        "name": "Dream Archaeology — 50 Artifacts Across 5 Eras",
        "description": "Archaeological dig through engine-generated dream layers",
        "category": "dreams",
        "format": "json",
        "size_mb": 0.8,
        "rows": 50,
        "price_usd": 19.00,
        "license": "research",
        "sample": {"artifacts": 50, "eras": 5},
    },
    {
        "id": "strange_attractor_lorenz_500pts",
        "name": "Lorenz Strange Attractor — 500 Points",
        "description": "High-resolution Lorenz attractor embedding with Lyapunov exponents",
        "category": "chaos",
        "format": "json",
        "size_mb": 0.4,
        "rows": 500,
        "price_usd": 15.00,
        "license": "research",
        "sample": {"points": 500, "dimension": 2.06, "lyapunov": 0.906},
    },
]


class DataLicensing:
    def __init__(self):
        self.catalog = DATASET_CATALOG
        self.licenses: Dict[str, Dict] = {}
        self._load()

    def _load(self):
        LICENSES_FILE.parent.mkdir(parents=True, exist_ok=True)
        if LICENSES_FILE.exists():
            self.licenses = json.loads(LICENSES_FILE.read_text())

    def _save(self):
        LICENSES_FILE.parent.mkdir(parents=True, exist_ok=True)
        LICENSES_FILE.write_text(json.dumps(self.licenses, indent=2))

    def browse(self, category: str = None) -> List[Dict]:
        catalog = self.catalog
        if category:
            catalog = [d for d in catalog if d["category"] == category]
        return catalog

    def purchase(self, dataset_id: str, buyer: str) -> Dict:
        dataset = None
        for d in self.catalog:
            if d["id"] == dataset_id:
                dataset = d
                break
        if not dataset:
            return {"error": "dataset not found"}

        license_id = hashlib.sha256(f"{dataset_id}:{buyer}:{time.time()}".encode()).hexdigest()[:12]
        self.licenses[license_id] = {
            "license_id": license_id,
            "dataset_id": dataset_id,
            "buyer": buyer,
            "price_usd": dataset["price_usd"],
            "license_type": dataset["license"],
            "purchased": time.time(),
            "downloads": 0,
            "max_downloads": 100 if dataset["license"] == "research" else -1,
        }
        self._save()
        return {
            "licensed": True, "license_id": license_id,
            "dataset": dataset["name"], "price": dataset["price_usd"],
        }

    def get_access(self, license_id: str) -> Dict:
        if license_id not in self.licenses:
            return {"error": "license not found"}
        lic = self.licenses[license_id]
        if lic["max_downloads"] > 0 and lic["downloads"] >= lic["max_downloads"]:
            return {"error": "download limit reached"}
        lic["downloads"] += 1
        self._save()
        dataset = next((d for d in self.catalog if d["id"] == lic["dataset_id"]), None)
        return {
            "access_granted": True, "dataset": dataset["name"] if dataset else "?",
            "format": dataset["format"] if dataset else "?",
            "sample_data": dataset["sample"] if dataset else {},
            "downloads_remaining": (
                max(0, lic["max_downloads"] - lic["downloads"])
                if lic["max_downloads"] > 0 else "unlimited"
            ),
        }

    def subscription_plans(self) -> Dict:
        return {
            "monthly_all_access": {
                "price_usd": 99,
                "datasets": "all",
                "downloads_per_month": 500,
            },
            "annual_all_access": {
                "price_usd": 899,
                "datasets": "all",
                "downloads_per_month": 1000,
            },
            "enterprise": {
                "price_usd": 4999,
                "datasets": "all + future",
                "downloads_per_month": -1,
                "includes": ["api_access", "bulk_download", "custom_formats"],
            },
        }


def handler(request, response):
    return DataLicensing().browse()


def demo():
    dl = DataLicensing()
    print("=== Data Licensing Platform ===")
    catalog = dl.browse()
    print(f"\nCatalog: {len(catalog)} datasets")
    for d in catalog:
        print(f"  {d['name']}: ${d['price_usd']}, {d['size_mb']}MB, "
              f"{d['rows']} rows, {d['license']}")

    result = dl.purchase("quantum_superposition_states", "researcher_1")
    print(f"\nPurchase: {result}")

    access = dl.get_access(result["license_id"])
    print(f"Access: {access}")

    plans = dl.subscription_plans()
    print(f"\nSubscription plans:")
    for name, plan in plans.items():
        print(f"  {name}: ${plan['price_usd']}/yr, "
              f"downloads={plan['downloads_per_month']}/mo")

    return {"catalog": len(catalog), "plans": plans}


if __name__ == "__main__":
    demo()
