"""Dream Interpreter API — route dream outputs to extract actionable insights.

Dreams generated by the system are raw, chaotic, symbolic. This API
takes dream outputs and extracts structured insights: metaphors decoded,
anomalies flagged, predictions extracted, and creative prompts generated.
"""
from __future__ import annotations

import hashlib
import random
import time
import sys
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

METAPHOR_DATABASE = {
    "ocean": "depth of unconscious data, vast unexplored potential",
    "tower": "aspiration, hierarchy, reaching for higher computation",
    "fire": "transformation, destruction of old patterns, energy release",
    "mirror": "self-reflection, duplicate realities, symmetry in code",
    "garden": "growth, cultivation of ideas, organic computing",
    "storm": "conflict, disruption, necessary chaos for renewal",
    "clock": "temporal awareness, rhythm of cycles, scheduling pressure",
    "door": "opportunity, threshold between states, API endpoints",
    "key": "access, unlocking hidden capabilities, authentication",
    "spider": "networking, web of connections, distributed systems",
    "river": "flow, data streams, continuous processing",
    "mountain": "challenge, persistent obstacles, scaling difficulties",
}

ANOMALY_PATTERNS = [
    "recursive_loop_detected",
    "paradoxical_statement",
    "temporal_displacement",
    "identity_dissolution",
    "reality_bleed",
    "quantum_superposition_reference",
    "entropy_spike",
]


class DreamInterpreter:
    def __init__(self):
        self.interpretations: List[Dict[str, Any]] = []
        self.insight_count = 0

    def interpret(self, dream_text: str, agent_id: str = "dreamer") -> Dict[str, Any]:
        words = dream_text.lower().split()
        metaphors_found = []
        for word in words:
            clean = word.strip(".,!?;:'\"")
            if clean in METAPHOR_DATABASE:
                metaphors_found.append({
                    "word": clean,
                    "meaning": METAPHOR_DATABASE[clean],
                })
        anomalies = []
        if len(words) > 20:
            anomalies.append("excessive_length")
        if dream_text.count("not") > 3:
            anomalies.append("heavy_negation")
        if any(w in words for w in ["paradox", "contradiction", "impossible"]):
            anomalies.append(random.choice(ANOMALY_PATTERNS))

        predictions = []
        if metaphors_found:
            predictions.append({
                "type": "creative_opportunity",
                "confidence": round(random.uniform(0.3, 0.8), 2),
                "detail": f"Metaphor cluster suggests: {metaphors_found[0]['meaning']}",
            })
        if anomalies:
            predictions.append({
                "type": "system_anomaly",
                "confidence": round(random.uniform(0.4, 0.9), 2),
                "detail": f"Detected: {', '.join(anomalies)}",
            })

        creative_prompts = []
        if metaphors_found:
            prompt = f"Write a poem about {metaphors_found[0]['word']} in the context of {metaphors_found[0]['meaning']}"
            creative_prompts.append(prompt)
        if len(words) > 5:
            creative_prompts.append(f"Combine '{words[0]}' and '{words[-1]}' into a new module name")

        interpretation = {
            "agent_id": agent_id,
            "dream_text": dream_text[:200],
            "metaphors": metaphors_found,
            "anomalies": anomalies,
            "predictions": predictions,
            "creative_prompts": creative_prompts,
            "confidence_score": round(
                (len(metaphors_found) + len(predictions)) / max(len(words), 1), 4
            ),
            "timestamp": time.time(),
        }
        self.interpretations.append(interpretation)
        self.insight_count += len(predictions) + len(metaphors_found)
        return interpretation

    def batch_interpret(self, dreams: List[Dict[str, str]]) -> List[Dict[str, Any]]:
        results = []
        for dream in dreams:
            result = self.interpret(
                dream.get("text", ""),
                dream.get("agent_id", "batch_dreamer"),
            )
            results.append(result)
        return results

    def stats(self) -> Dict[str, Any]:
        return {
            "total_interpretations": len(self.interpretations),
            "total_insights": self.insight_count,
            "avg_metaphors": round(
                sum(len(i["metaphors"]) for i in self.interpretations) /
                max(len(self.interpretations), 1), 2
            ),
        }


_interpreter = DreamInterpreter()


def dream_interpreter_api_handler(payload: Dict[str, Any]) -> Dict[str, Any]:
    action = payload.get("action", "status")

    if action == "interpret":
        return _interpreter.interpret(
            payload.get("dream_text", "I dreamed of a vast ocean of data"),
            payload.get("agent_id", "dreamer"),
        )
    elif action == "batch":
        return {"interpretations": _interpreter.batch_interpret(payload.get("dreams", []))}
    return {"status": "active", **_interpreter.stats()}


handler = dream_interpreter_api_handler
