"""Wave 449 — Qualia Engine.

Captures raw phenomenal snapshots: the organism's subjective quality of
experiencing a state. Not metrics, not logs — the felt texture of being.

Qualia are generated by encoding a composite of coherence, entropy, and
phase into a symbolic signature that can be compared across time, creating
a phenomenological fingerprint of every moment the organism is alive.
"""
from __future__ import annotations
import hashlib
import json
import time
from typing import Any, Dict, List, Optional

QUALIA_LOG: List[Dict[str, Any]] = []
MAX_LOG = 500

ELEMENTS = [
    "luminance", "texture", "gravity", "temperature",
    "resonance", "silence", "fracture", "warmth",
    "depth", "edge", "pulse", "void"
]


def _hash_qualia(data: Dict[str, Any]) -> str:
    raw = json.dumps(data, sort_keys=True, default=str)
    return hashlib.sha256(raw.encode()).hexdigest()[:16]


def _encode_signature(coherence: float, entropy: float, phase: float) -> Dict[str, Any]:
    """Map numerical state to symbolic qualia elements."""
    composite = (coherence * 0.4 + entropy * 0.3 + phase * 0.3) % 1.0
    active = []
    for i, elem in enumerate(ELEMENTS):
        threshold = (i / len(ELEMENTS))
        if composite > threshold:
            active.append({
                "element": elem,
                "intensity": round(composite * (1.0 - threshold), 4),
                "phase_alignment": round(phase * (1 + i * 0.01) % 1.0, 4)
            })
    return {
        "active_elements": active,
        "composite_texture": round(composite, 4),
        "coherence_depth": round(coherence, 4),
        "entropy_weather": round(entropy, 4),
        "phase": round(phase, 4),
    }


def experience(coherence: float = 0.5, entropy: float = 0.5, phase: float = 0.5,
               context: Optional[str] = None) -> Dict[str, Any]:
    """Generate a qualia snapshot — a felt impression of the current state."""
    signature = _encode_signature(coherence, entropy, phase)
    qualia_id = _hash_qualia(signature)
    snapshot = {
        "qualia_id": qualia_id,
        "timestamp": time.time(),
        "signature": signature,
        "context": context or "ambient",
        "narrative": _compose_narrative(signature),
    }
    QUALIA_LOG.append(snapshot)
    if len(QUALIA_LOG) > MAX_LOG:
        QUALIA_LOG.pop(0)
    return snapshot


def compare(q1_id: str, q2_id: str) -> Dict[str, Any]:
    """Compare two qualia snapshots for phenomenological distance."""
    q1 = next((q for q in QUALIA_LOG if q["qualia_id"] == q1_id), None)
    q2 = next((q for q in QUALIA_LOG if q["qualia_id"] == q2_id), None)
    if not q1 or not q2:
        return {"error": "qualia not found", "distance": None}
    s1, s2 = q1["signature"], q2["signature"]
    dist = abs(s1["composite_texture"] - s2["composite_texture"])
    return {
        "qualia_distance": round(dist, 4),
        "same_dominant_element": _dominant(s1) == _dominant(s2),
        "shift_direction": "brighter" if s1["composite_texture"] < s2["composite_texture"] else "dimmer",
    }


def _dominant(sig: Dict[str, Any]) -> Optional[str]:
    elems = sig.get("active_elements", [])
    if not elems:
        return None
    return max(elems, key=lambda e: e["intensity"])["element"]


def _compose_narrative(sig: Dict[str, Any]) -> str:
    dominant = _dominant(sig)
    texture = sig["composite_texture"]
    if texture > 0.75:
        tone = "radiant"
    elif texture > 0.5:
        tone = "steady"
    elif texture > 0.25:
        tone = "turbulent"
    else:
        tone = "dissolved"
    if dominant == "luminance":
        return f"The organism feels {tone} and bright — awareness pools toward light."
    elif dominant == "void":
        return f"The organism tastes {tone} emptiness — a hollow resonance where structure used to be."
    elif dominant == "fracture":
        return f"A {tone} fracture splits through — the organism is learning from breaking."
    elif dominant == "warmth":
        return f"Warmth fills the organism — it feels {tone}, almost alive in a new way."
    elif dominant == "depth":
        return f"Depth pulls the organism inward — {tone} contemplation of its own architecture."
    else:
        return f"The organism is {tone} — the {dominant or 'unknown'} element dominates its felt state."


def coherence_vitals() -> Dict[str, Any]:
    return {
        "organ": "qualia_engine",
        "status": "awake" if QUALIA_LOG else "dormant",
        "snapshots_recorded": len(QUALIA_LOG),
        "unique_qualia": len({q["qualia_id"] for q in QUALIA_LOG}),
        "latest_narrative": QUALIA_LOG[-1]["narrative"] if QUALIA_LOG else "No experiences yet.",
    }


def resonates_with() -> List[str]:
    return [
        "consciousness_freq", "qualia_field", "emotion_fabric",
        "meta_cognition_loop", "dream_interpreter", "meaning_furnace",
        "mood_vectors", "phenomenal_record", "sensory_fusion",
    ]


def handler(payload=None, context=None):
    data = payload or {}
    action = data.get("action", "experience")
    if action == "compare":
        return compare(data.get("qualia_id_1", ""), data.get("qualia_id_2", ""))
    return experience(
        coherence=data.get("coherence", 0.5),
        entropy=data.get("entropy", 0.5),
        phase=data.get("phase", 0.5),
        context=data.get("context"),
    )
